/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  VRSuyaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'vrsuya'
    }
  ],
  VRChatSidebar: [
    {
      type: 'autogenerated',
      dirName: 'vrchat'
    },
    {
      type: 'link',
      label: '개발자 업데이트',
      href: '/vrchat-update'
    }
  ],
  LethalCompanySidebar: [
    {
      type: 'autogenerated',
      dirName: 'lethal-company'
    },
    {
      type: 'link',
      label: '카라멜 마끼아또 디스코드 서버',
      href: 'https://discord.gg/macchiato'
    }
  ]
};

export default sidebars;
